language: node_js
sudo: false
node_js:
- iojs-v1
cache:
  directories:
  - node_modules
notifications:
  email: false
after_success:
- npm run deploy
env:
  global:
  - secure: E0+36QbQ1WhAczZX8u7pqG+yD+aGDfDJnZoAAVLioHXVrS2rop3roSwMi5GX5JdBKsdJ8FOebS4BK7WogxiBMS+sf5bhsDGx7QkfGJA5ziRhEB7A6jygf9JENsnziOUaIGDQI5rOgoGIums3CM+q39+/YtKY8ARfj9lcPUegVKQ=
