language: node_js
# currently broken "netstat: not found"
# sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
after_success:
- npm run deploy
env:
  global:
    secure: hfC7rdkZIU8zn+zZrycdAeQWYUKBhIW4ZAst2ejce05yNI5pEVy7IO42TLRO3ncT0wX8jiyEiIx1tBHW9OnmQzF7NR7Sf9DIpR7iBGNJt0bsWrmesIJHPBSI7zoV2m1EtMtwVxOyGP+yiXVSJ7RExmOAJmBqnVDoraBasevHTME=
